name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          # - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
          cache: "npm"

      - name: Install canvas dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install pkg-config cairo pango libpng jpeg giflib librsvg

      - name: Install canvas dependencies on Windows
        if: ${{ runner.os == 'Windows' }}
        run: mkdir C:\\GTK && curl -o gtk.zip https://mirror.ossplanet.net/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip && tar xvf gtk.zip -C C:\\GTK

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Distribution
        run: npm exec electron-builder -- -p never --dir
